

export const bikes = [
    {
        _id:'01',
        name:'YAMAHA MT09',
        brand:'yamaha',
        model: 'mt09',
        price:'4,500',
        year:'2021',
        type:'sports',
        engineType:'4-Stroke Cylinder',
        power:'205hp (151 kW)',
        displacement:'1103',
        stroke:'80mm / 49.7mm',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text',
        thumbnail:'https://images.pexels.com/photos/39693/motorcycle-racer-racing-race-speed-39693.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260'
    },
    {
        _id:'02',
        name:'YAMAHA MT09',
        brand:'yamaha',
        model: 'mt09',
        price:'4,500',
        year:'2021',
        type:'sports',
        engineType:'4-Stroke Cylinder',
        power:'205hp (151 kW)',
        displacement:'1103',
        stroke:'80mm / 49.7mm',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text',
        thumbnail:'https://images.pexels.com/photos/39693/motorcycle-racer-racing-race-speed-39693.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260'
    },
    {
        _id:'03',
        name:'YAMAHA MT09',
        brand:'yamaha',
        model: 'mt09',
        price:'4,500',
        year:'2021',
        type:'sports',
        engineType:'4-Stroke Cylinder',
        power:'205hp (151 kW)',
        displacement:'1103',
        stroke:'80mm / 49.7mm',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text',
        thumbnail:'https://images.pexels.com/photos/39693/motorcycle-racer-racing-race-speed-39693.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260'
    },
    {
        _id:'04',
        name:'YAMAHA MT09',
        brand:'yamaha',
        model: 'mt09',
        price:'4,500',
        year:'2021',
        type:'sports',
        engineType:'4-Stroke Cylinder',
        power:'205hp (151 kW)',
        displacement:'1103',
        stroke:'80mm / 49.7mm',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text',
        thumbnail:'https://images.pexels.com/photos/39693/motorcycle-racer-racing-race-speed-39693.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260'
    },
    {
        _id:'05',
        name:'YAMAHA MT09',
        brand:'yamaha',
        model: 'mt09',
        price:'4,500',
        year:'2021',
        type:'sports',
        engineType:'4-Stroke Cylinder',
        power:'205hp (151 kW)',
        displacement:'1103',
        stroke:'80mm / 49.7mm',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text',
        thumbnail:'https://images.pexels.com/photos/39693/motorcycle-racer-racing-race-speed-39693.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260'
    },
    {
        _id:'06',
        name:'YAMAHA MT09',
        brand:'yamaha',
        model: 'mt09',
        price:'4,500',
        year:'2021',
        type:'sports',
        engineType:'4-Stroke Cylinder',
        power:'205hp (151 kW)',
        displacement:'1103',
        stroke:'80mm / 49.7mm',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text',
        thumbnail:'https://images.pexels.com/photos/39693/motorcycle-racer-racing-race-speed-39693.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260'
    }
]